version: '3.5'

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"   # HTTP API port
      - "6334:6334"   # gRPC port
    volumes:
      - ${HOME}/qdrant_data:/qdrant/storage
